package com.tradingplatform.domain.service;

import com.tradingplatform.domain.dto.PlaceOrderRequest;
import com.tradingplatform.domain.exception.AccountNotActiveException;
import com.tradingplatform.domain.exception.AccountNotFoundException;
import com.tradingplatform.domain.exception.DuplicateOrderException;
import com.tradingplatform.domain.exception.InstrumentNotFoundException;
import com.tradingplatform.domain.exception.InsufficientFundsException;
import com.tradingplatform.domain.exception.InsufficientHoldingsException;
import com.tradingplatform.domain.exception.InvalidOrderException;
import com.tradingplatform.domain.model.Account;
import com.tradingplatform.domain.model.Instrument;
import com.tradingplatform.domain.model.Money;
import com.tradingplatform.domain.model.Order;
import com.tradingplatform.domain.model.OrderSide;
import com.tradingplatform.domain.model.Position;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

/**
 * Business rules 1 to 8 for placing an order.
 *
 * <p>The rules live here, not in a controller and not in a mapper. A controller that carries a rule
 * cannot be tested without a servlet container and cannot be reused by the Trade Executor. Every
 * rule in this class is exercised by {@code OrderLogicTest} with plain objects and no framework.
 *
 * <p>The rules are evaluated in the order below and the first failure wins. No later rule runs. The
 * ordering is part of the contract, because it decides which error a request that breaks two rules
 * receives, and the Angular UI branches on that code.
 *
 * <table>
 *   <caption>Evaluation order</caption>
 *   <tr><th>#</th><th>Rule</th><th>Failure</th></tr>
 *   <tr><td>1</td><td>The account exists</td><td>{@code ACC-404}</td></tr>
 *   <tr><td>2</td><td>The account is ACTIVE</td><td>{@code ACC-403}</td></tr>
 *   <tr><td>3</td><td>The instrument exists and is tradable</td><td>{@code INS-404}</td></tr>
 *   <tr><td>4</td><td>Quantity is greater than zero</td><td>{@code VAL-422}</td></tr>
 *   <tr><td>5</td><td>Price is greater than zero</td><td>{@code VAL-422}</td></tr>
 *   <tr><td>6</td><td>BUY: cash covers quantity times price</td><td>{@code ORD-400}</td></tr>
 *   <tr><td>7</td><td>SELL: holding covers the quantity</td><td>{@code ORD-409}</td></tr>
 *   <tr><td>8</td><td>The idempotency key is unused</td><td>{@code ORD-409}</td></tr>
 * </table>
 *
 * <p>Rules 9 and 10 have no error code and are not enforced here. They say that cash and position
 * update atomically and that every order is recorded, including a rejected one. Placement records
 * intent and moves no money, so those two belong to {@link SettlementService} and to the
 * transaction boundary in the Trade REST API.
 *
 * <p>The class holds no state beyond its registry and is safe to share between threads.
 */
public class OrderPlacementService {

    private final IdempotencyKeyRegistry idempotencyKeyRegistry;

    /**
     * Builds a service that defers business rule 8 to the unique constraint on
     * {@code orders.idempotency_key}. This is the constructor the Trade REST API uses.
     */
    public OrderPlacementService() {
        this(IdempotencyKeyRegistry.none());
    }

    public OrderPlacementService(IdempotencyKeyRegistry idempotencyKeyRegistry) {
        this.idempotencyKeyRegistry =
                Objects.requireNonNull(idempotencyKeyRegistry, "idempotencyKeyRegistry");
    }

    /**
     * Applies rules 1 to 8 and returns an accepted order in status {@code NEW}.
     *
     * <p>Nothing is mutated. The account balance and the position are read, never written: an
     * accepted order is a record of intent, and the money moves at settlement.
     *
     * @param request    the validated request
     * @param account    the account addressed, or null when no such row exists
     * @param instrument the instrument addressed, or null when no such row exists
     * @param position   the current holding, or null when the account holds none
     * @param orderId    identifier to assign, generated by the caller so that the caller can log it
     *                   before the insert
     * @param createdOn  acceptance time, supplied rather than read from the system clock so that the
     *                   rules are testable and the recorded time matches the row the caller writes
     * @return an order in status NEW, not yet persisted
     */
    public Order placeOrder(PlaceOrderRequest request,
                            Account account,
                            Instrument instrument,
                            Position position,
                            UUID orderId,
                            Instant createdOn) {
        Objects.requireNonNull(request, "request");
        Objects.requireNonNull(orderId, "orderId");
        Objects.requireNonNull(createdOn, "createdOn");

        requireAccountExists(request, account);
        requireAccountActive(account);
        requireTradableInstrument(request, instrument);
        requirePositiveQuantity(request);
        requirePositivePrice(request);
        requireAffordable(request, account);
        requireHoldings(request, position);
        requireUnusedIdempotencyKey(request);

        return Order.accept(
                orderId,
                account.getId(),
                request.symbol(),
                request.side(),
                request.quantity(),
                request.price(),
                request.idempotencyKey(),
                createdOn);
    }

    /** Rule 1. */
    private static void requireAccountExists(PlaceOrderRequest request, Account account) {
        if (account == null) {
            throw new AccountNotFoundException(request.accountId());
        }
    }

    /** Rule 2. */
    private static void requireAccountActive(Account account) {
        if (!account.isActive()) {
            throw new AccountNotActiveException(account.getId(), account.getStatus());
        }
    }

    /** Rule 3. An unknown instrument and a suspended one are the same answer to the caller. */
    private static void requireTradableInstrument(PlaceOrderRequest request, Instrument instrument) {
        if (instrument == null || !instrument.isTradable()) {
            throw new InstrumentNotFoundException(request.symbol());
        }
    }

    /** Rule 4. */
    private static void requirePositiveQuantity(PlaceOrderRequest request) {
        Integer quantity = request.quantity();
        if (quantity == null || quantity <= 0) {
            throw new InvalidOrderException("quantity", "must be greater than zero");
        }
    }

    /** Rule 5. */
    private static void requirePositivePrice(PlaceOrderRequest request) {
        if (!Money.isPositive(request.price())) {
            throw new InvalidOrderException("price", "must be greater than zero");
        }
    }

    /** Rule 6. Buys only. A sell releases cash rather than consuming it. */
    private static void requireAffordable(PlaceOrderRequest request, Account account) {
        if (request.side() != OrderSide.BUY) {
            return;
        }
        BigDecimal required = Money.consideration(request.quantity(), request.price());
        if (!account.canAfford(required)) {
            throw new InsufficientFundsException(required, account.getCashBalance());
        }
    }

    /** Rule 7. Sells only. A null position means the account holds nothing at all. */
    private static void requireHoldings(PlaceOrderRequest request, Position position) {
        if (request.side() != OrderSide.SELL) {
            return;
        }
        int held = position == null ? 0 : position.getQuantity();
        if (held < request.quantity()) {
            throw new InsufficientHoldingsException(request.symbol(), request.quantity(), held);
        }
    }

    /** Rule 8. Last, because it is the most expensive to check and the least likely to fire. */
    private void requireUnusedIdempotencyKey(PlaceOrderRequest request) {
        if (idempotencyKeyRegistry.isKnown(request.idempotencyKey())) {
            throw new DuplicateOrderException(request.idempotencyKey());
        }
    }
}
